/**
 * 150 bilingual (EN + AR) motivational messages for studying.
 * Each entry: { en, ar }
 */
export const MOTIVATIONAL_QUOTES = [
  { en: "Small steps every day lead to big results.", ar: "خطوات صغيرة كل يوم تؤدي إلى نتائج كبيرة." },
  { en: "You don't have to be perfect — just consistent.", ar: "مش لازم تكون مثالي، بس كن منتظم." },
  { en: "One more word today is one less tomorrow.", ar: "كلمة زيادة النهاردة = كلمة أقل بكرة." },
  { en: "Focus for 25 minutes. Rest. Repeat.", ar: "ركز 25 دقيقة. ارتاح. كرر." },
  { en: "Your future self is watching — make them proud.", ar: "نسختك المستقبلية بتشوفك — خليها تفخر بيك." },
  { en: "Progress, not perfection.", ar: "التقدّم، مش الكمال." },
  { en: "The hardest part is starting. You've already started.", ar: "أصعب حاجة البداية. وأنت بدأت خلاص." },
  { en: "Every expert was once a beginner.", ar: "كل خبير كان مبتدئ في يوم من الأيام." },
  { en: "Study while others sleep. Rise while others rest.", ar: "ادرس وناس نايمة. قوم وناس لسه بترتاح." },
  { en: "Discipline beats motivation when motivation fades.", ar: "الانضباط بيفوز على الحماس لما الحماس يضعف." },
  { en: "You are building a skill, not chasing a grade.", ar: "إنت بتبني مهارة، مش بتطارد درجة." },
  { en: "Mistakes are proof that you are trying.", ar: "الأخطاء دليل إنك بتحاول." },
  { en: "A little each day adds up to a lot.", ar: "القليل كل يوم بيتراكم لكتير." },
  { en: "Don't count the days. Make the days count.", ar: "متعدش الأيام. خلّي الأيام تعدّ." },
  { en: "Your only competition is who you were yesterday.", ar: "منافسك الوحيد هو أنت امبارح." },
  { en: "Clarity comes from action, not from waiting.", ar: "الوضوح بيجي من الفعل، مش من الانتظار." },
  { en: "Protect your study time like an important meeting.", ar: "احمِ وقت مذاكرتك كأنه اجتماع مهم." },
  { en: "Tired is temporary. Regret can last longer.", ar: "التعب مؤقت. الندم ممكن يطول." },
  { en: "You are allowed to rest — not to quit.", ar: "مسموح لك ترتاح، مش تسيّب." },
  { en: "Show up even when you don't feel like it.", ar: "احضر حتى لو مش حاسس إنك عايز." },
  { en: "Learning a language is a marathon, not a sprint.", ar: "تعلّم اللغة ماراثون، مش سباق سرعة." },
  { en: "Review is how memory becomes permanent.", ar: "المراجعة هي اللي بتخلي الذاكرة ثابتة." },
  { en: "The word you struggle with today will be easy next week.", ar: "الكلمة اللي بتعاندك النهاردة هتبقى سهلة الأسبوع الجاي." },
  { en: "Put your phone away for one focused session.", ar: "سيّب الموبايل بعيد جلسة تركيز واحدة." },
  { en: "Consistency compounds. Keep going.", ar: "الانتظام بيتضاعف. كمّل." },
  { en: "You are closer than you think.", ar: "إنت أقرب مما تتخيّل." },
  { en: "Breathe. Open the list. Start with one word.", ar: "خُد نفس. افتح القائمة. ابدأ بكلمة واحدة." },
  { en: "Effort is the one thing fully under your control.", ar: "المجهود هو الحاجة الوحيدة اللي تحت سيطرتك بالكامل." },
  { en: "Today's review saves tomorrow's stress.", ar: "مراجعة النهاردة بتوفّر توتر بكرة." },
  { en: "Be proud of showing up.", ar: "افخر إنك حضرت." },
  { en: "Slow progress is still progress.", ar: "التقدّم البطيء لسه تقدّم." },
  { en: "Your brain grows when it's challenged.", ar: "مخك بيكبر لما يتحدّى." },
  { en: "Done is better than perfect when you're learning.", ar: "المُنجَز أحسن من المثالي وأنت بتتعلّم." },
  { en: "Turn 'I have to study' into 'I get to improve'.", ar: "حوّل «لازم أذاكر» إلى « downstreamني أتطوّر»." },
  { en: "A focused hour beats a distracted afternoon.", ar: "ساعة تركيز أحسن من ضهر مشتّت." },
  { en: "You are training your future fluency.", ar: "إنت بتدرّب طلاقتك المستقبلية." },
  { en: "Skip the scroll. Open the deck.", ar: "سيّب السكرول. افتح البطاقات." },
  { en: "Courage is studying when it's hard.", ar: "الشجاعة إنك تذاكر لما تبقى صعبة." },
  { en: "Your notes are a gift to future you.", ar: "ملاحظاتك هدية لنسختك المستقبلية." },
  { en: "One session at a time.", ar: "جلسة واحدة في كل مرة." },
  { en: "The discomfort of learning is temporary.", ar: "عدم راحة التعلّم مؤقتة." },
  { en: "Keep the streak. Protect the habit.", ar: "حافظ على السلسلة. احمِ العادة." },
  { en: "You don't need more time — you need more focus.", ar: "مش محتاج وقت أكتر — محتاج تركيز أكتر." },
  { en: "Read it. Say it. Write it. Use it.", ar: "اقرأها. قولها. اكتبها. استخدمها." },
  { en: "Doubt kills more dreams than failure does.", ar: "الشك بيقتل أحلام أكتر من الفشل." },
  { en: "Start messy. Improve as you go.", ar: "ابدأ فوضوي. حسّن وأنت ماشي." },
  { en: "Your effort today is interest on tomorrow's success.", ar: "مجهودك النهاردة فوايد على نجاح بكرة." },
  { en: "Silence the noise. Serve the goal.", ar: "اسكت الضوضاء. خدم الهدف." },
  { en: "You are allowed to be a beginner.", ar: "مسموح لك تكون مبتدئ." },
  { en: "Memorize less. Review more.", ar: "احفظ أقل. راجع أكتر." },
  { en: "Action cures anxiety about studying.", ar: "الفعل بيعالج القلق من المذاكرة." },
  { en: "Make it easy to start: open the app first.", ar: "سهّل البداية: افتح التطبيق الأول." },
  { en: "Hard days build strong habits.", ar: "الأيام الصعبة بتبني عادات قوية." },
  { en: "You are not behind. You are on your path.", ar: "إنت مش متأخر. إنت على طريقك." },
  { en: "Celebrate small wins out loud.", ar: "احتفل بالانتصارات الصغيرة بصوت عالي." },
  { en: "The best time to study was yesterday. The next best is now.", ar: "أحسن وقت للمذاكرة كان امبارح. اللي بعده دلوقتي." },
  { en: "Replace 'I can't' with 'I'm learning how'.", ar: "بدّل «مش قادر» بـ «بتعلّم إزاي»." },
  { en: "Your attention is your most valuable study tool.", ar: "انتباهك أغلى أداة مذاكرة عندك." },
  { en: "Keep going. The breakthrough is often near.", ar: "كمّل. الانفراجة غالبًا قريبة." },
  { en: "Study with purpose, not pressure.", ar: "ذاكر بهدف، مش بضغط." },
  { en: "A clear desk and a clear list help a clear mind.", ar: "مكتب مرتب وقائمة واضحة يساعدوا عقل صافي." },
  { en: "You owe yourself the chance to improve.", ar: "إنت مدين لنفسك بفرصة التطوّر." },
  { en: "Repetition is the mother of mastery.", ar: "التكرار أمّ الإتقان." },
  { en: "Don't wait for inspiration. Create momentum.", ar: "متستناش الإلهام. اخلق زخم." },
  { en: "Today's vocabulary is tomorrow's conversation.", ar: "مفردات النهاردة محادثة بكرة." },
  { en: "Be kind to yourself and strict with your schedule.", ar: "كن لطيف مع نفسك وصارم مع جدولك." },
  { en: "Finish this session. Then rest well.", ar: "خلّص الجلسة دي. وبعدين ارتاح كويس." },
  { en: "Confidence comes after competence — keep practicing.", ar: "الثقة بتيجي بعد الكفاءة — كمّل تمرين." },
  { en: "You are collecting wins, one word at a time.", ar: "إنت بتجمّع انتصارات، كلمة بكلمة." },
  { en: "When it feels hard, you're growing.", ar: "لما تحس إنها صعبة، يبقى إنت بتكبر." },
  { en: "Plan the session. Then protect it.", ar: "خطّط للجلسة. وبعدين احميها." },
  { en: "Your future fluency is built in quiet hours.", ar: "طلاقتك المستقبلية بتتبني في الساعات الهادية." },
  { en: "Stop negotiating with yourself. Just begin.", ar: "بطّل تفاوض مع نفسك. ابدأ بس." },
  { en: "Quality minutes beat empty hours.", ar: "دقائق بجودة أحسن من ساعات فاضية." },
  { en: "You can do hard things.", ar: "تقدر تعمل حاجات صعبة." },
  { en: "Learning loves a calm, steady pace.", ar: "التعلّم بيحب إيقاع هادي وثابت." },
  { en: "Put energy into what you can control.", ar: "حط طاقتك في اللي تحت سيطرتك." },
  { en: "Every review is a deposit in your memory bank.", ar: "كل مراجعة إيداع في بنك ذاكرتك." },
  { en: "Stay curious. Curiosity makes study lighter.", ar: "فضولي. الفضول بيخلّي المذاكرة أخف." },
  { en: "You are not stuck — you are in the middle of the process.", ar: "إنت مش واقف — إنت في نص الطريق." },
  { en: "Choose progress over comfort for a little while.", ar: "اختار التقدّم على الراحة شوية." },
  { en: "A strong 'why' makes a hard 'how' easier.", ar: "«ليه» قوية بتخلي «إزاي» الصعبة أسهل." },
  { en: "Close the tabs. Open the lesson.", ar: "اقفل التابات. افتح الدرس." },
  { en: "Your pace is valid. Keep moving.", ar: "إيقاعك مقبول. فضّل تمشي." },
  { en: "Practice until the awkward becomes automatic.", ar: "تمرّن لحد ما الغريب يبقى تلقائي." },
  { en: "The goal is not to finish fast — it's to finish strong.", ar: "الهدف مش تخلّص بسرعة — الهدف تخلّص قوي." },
  { en: "Write it down. Speaking it seals it.", ar: "اكتبها. قولها بيثبّتها." },
  { en: "You are allowed to restart your focus as many times as needed.", ar: "مسموح تعيد التركيز قد ما تحتاج." },
  { en: "Make studying the easiest choice in the room.", ar: "خلّي المذاكرة أسهل اختيار في المكان." },
  { en: "Results follow habits. Build the habit.", ar: "النتائج بتتبع العادات. ابنِ العادة." },
  { en: "One focused review is better than none.", ar: "مراجعة مركّزة واحدة أحسن من ولا حاجة." },
  { en: "Trust the process. Trust your effort.", ar: "ثق في العملية. ثق في مجهودك." },
  { en: "You are rewriting what you believe you can do.", ar: "إنت بتعيد كتابة اللي بتفتكر إنك تقدر تعمله." },
  { en: "Keep the session short if needed — but keep it real.", ar: "خلّي الجلسة قصيرة لو محتاج — بس خلّيها حقيقية." },
  { en: "The list gets shorter when you stay with it.", ar: "القائمة بتقصر لما تفضل معاها." },
  { en: "Your mind is trainable. Train it today.", ar: "عقلك قابل للتدريب. درّبه النهاردة." },
  { en: "Borrow motivation from your goals, not from your mood.", ar: "خد الحماس من أهدافك، مش من مزاجك." },
  { en: "Show respect to your time by using it well.", ar: "احترم وقتك باستخدامه كويس." },
  { en: "You are stacking skills that will serve you for years.", ar: "إنت بتكدّس مهارات هتخدمك سنين." },
  { en: "Less overthinking. More doing.", ar: "تفكير أقل. عمل أكتر." },
  { en: "A quiet study hour is a gift to your future.", ar: "ساعة مذاكرة هادية هدية لمستقبلك." },
  { en: "Keep your promises to yourself.", ar: "احفظ وعودك لنفسك." },
  { en: "The word that feels hard is the one worth learning.", ar: "الكلمة اللي بتحسها صعبة هي اللي تستاهل تتعلّم." },
  { en: "You improve every time you return.", ar: "بتحسّن كل مرة بترجع." },
  { en: "Focus is a muscle. Exercise it.", ar: "التركيز عضلة. مرّنها." },
  { en: "Don't compare chapters. Write yours.", ar: "متقارنش الفصول. اكتب فصلَك." },
  { en: "The finish line moves closer with every session.", ar: "خط النهاية بيقرب مع كل جلسة." },
  { en: "Rest is part of the plan — quitting is not.", ar: "الراحة جزء من الخطة — الاستسلام مش جزء." },
  { en: "You are capable of more than today's doubt suggests.", ar: "إنت قادر على أكتر مما بيقوله شك النهاردة." },
  { en: "Make the next right study choice.", ar: "اعمل اختيار المذاكرة الصح الجاي." },
  { en: "Language opens doors. Keep the key turning.", ar: "اللغة بتفتح أبواب. فضّل تلف المفتاح." },
  { en: "Your effort is visible in your growth.", ar: "مجهودك باين في نموّك." },
  { en: "Stay with the page a little longer.", ar: "اقعد مع الصفحة شوية زيادة." },
  { en: "Small consistent actions beat rare intensity.", ar: "أفعال صغيرة منتظمة بتفوز على حماس نادر." },
  { en: "You are not late. You are learning.", ar: "إنت مش متأخر. إنت بتتعلّم." },
  { en: "Turn pressure into a plan.", ar: "حوّل الضغط لخطة." },
  { en: "The habit is the achievement.", ar: "العادة هي الإنجاز." },
  { en: "Speak the word. Own the word.", ar: "قول الكلمة. امتلك الكلمة." },
  { en: "A good session starts with a clear first step.", ar: "الجلسة الكويسة بتبدأ بخطوة أولى واضحة." },
  { en: "You can restart your focus right now.", ar: "تقدر تعيد تركيزك دلوقتي." },
  { en: "Study is self-respect in action.", ar: "المذاكرة احترام للنفس على أرض الواقع." },
  { en: "Keep going through the boring middle.", ar: "كمّل في الجزء الممل في النص." },
  { en: "Your consistency will surprise you.", ar: "انتظامك هيفاجئك." },
  { en: "Choose the book over the feed for a while.", ar: "اختار الكتاب على الفيد شوية." },
  { en: "You are becoming someone who finishes.", ar: "إنت بتتطوّر لشخص بيخلّص." },
  { en: "Learning loves patience.", ar: "التعلّم بيحب الصبر." },
  { en: "Make today count with one solid session.", ar: "خلّي النهاردة لها قيمة بجلسة قوية واحدة." },
  { en: "The struggle is part of the story.", ar: "الصعوبة جزء من القصة." },
  { en: "Protect your energy for what matters.", ar: "احمِ طاقتك للي يهم." },
  { en: "You grow in the minutes you almost skipped.", ar: "بتنمو في الدقايق اللي كنت هتسيبها." },
  { en: "Keep the standard: show up and try.", ar: "حافظ على المعيار: احضر وحاول." },
  { en: "Fluency is built in ordinary days.", ar: "الطلاقة بتتبني في الأيام العادية." },
  { en: "Your next review is a chance to lock it in.", ar: "مراجعتك الجاية فرصة تثبّتها." },
  { en: "Be the student who returns.", ar: "كن الطالب اللي بيرجع." },
  { en: "The goal is growth, not a perfect score.", ar: "الهدف النمو، مش الدرجة المثالية." },
  { en: "You have enough to begin.", ar: "عندك كفاية عشان تبدأ." },
  { en: "Silence helps memory. Find a quiet corner.", ar: "الهدوء بيساعد الذاكرة. لاقي ركن هادي." },
  { en: "One honest hour changes the week.", ar: "ساعة صادقة واحدة بتغيّر الأسبوع." },
  { en: "You are allowed to improve slowly.", ar: "مسموح لك تتحسّن ببطء." },
  { en: "Stay loyal to the plan you made on a clear day.", ar: "كن وفي للخطة اللي عملتها في يوم صافي." },
  { en: "The work is simple: open, study, close, repeat.", ar: "الشغل بسيط: افتح، ذاكر، اقفل، كرر." },
  { en: "Your focus is a form of self-leadership.", ar: "تركيزك شكل من أشكال قيادة النفس." },
  { en: "Keep stacking ordinary wins.", ar: "فضّل تكدّس انتصارات عادية." },
  { en: "You will thank yourself for this session.", ar: "هتشكر نفسك على الجلسة دي." },
  { en: "Learning is a long friendship with effort.", ar: "التعلّم صداقة طويلة مع المجهود." },
  { en: "Start before you feel ready.", ar: "ابدأ قبل ما تحس إنك جاهز." },
  { en: "The path is made by walking it daily.", ar: "الطريق بيتبني بالمشي فيه كل يوم." },
  { en: "Your best study day can start in the next minute.", ar: "أحسن يوم مذاكرة ليك ممكن يبدأ في الدقيقة الجاية." },
  { en: "Hold the standard: a little better than yesterday.", ar: "حافظ على المعيار: أحسن شوية من امبارح." },
  { en: "You are building a life skill, not just a list.", ar: "إنت بتبني مهارة حياة، مش قائمة بس." },
  { en: "When motivation is low, let routine lead.", ar: "لما الحماس ينخفض، سيّب الروتين يقود." },
  { en: "A finished session is a quiet victory.", ar: "جلسة مخلّصة انتصار هادي." },
  { en: "Keep your promise for the next 20 minutes.", ar: "احفظ وعدك للعشرين دقيقة الجايين." },
  { en: "You are stronger than the urge to quit.", ar: "إنت أقوى من رغبة الاستسلام." },
  { en: "Study is how you invest in your options.", ar: "المذاكرة استثمار في اختياراتك." },
  { en: "Return to the words. They are waiting.", ar: "ارجع للكلمات. مستنياك." },
  { en: "Make this the session that turns the day around.", ar: "خلّي دي الجلسة اللي تقلب اليوم." },
  { en: "You don't need a perfect plan — you need the next step.", ar: "مش محتاج خطة مثالية — محتاج الخطوة الجاية." },
  { en: "Stay patient with the process and honest with the effort.", ar: "كن صبور مع العملية وصادق مع المجهود." },
  { en: "Your growth is happening in the quiet work.", ar: "نموّك بيحصل في الشغل الهادئ." },
  { en: "One more review. One more win.", ar: "مراجعة زيادة. انتصار زيادة." },
  { en: "You are worthy of the time you spend improving.", ar: "إنت تستاهل الوقت اللي بتصرفه على التطوّر." },
  { en: "Let today's work be enough for today.", ar: "خلّي شغل النهاردة يكفي لليوم." },
  { en: "The habit you protect today protects you later.", ar: "العادة اللي بتحميها النهاردة بتحميك بعدين." },
  { en: "Keep going — your future words depend on it.", ar: "كمّل — كلماتك المستقبلية معتمدة على كده." },
];

export function getRandomQuote(excludeIndex = -1) {
  const n = MOTIVATIONAL_QUOTES.length;
  if (n === 0) return { en: "", ar: "", index: -1 };
  let i = Math.floor(Math.random() * n);
  if (n > 1 && i === excludeIndex) {
    i = (i + 1 + Math.floor(Math.random() * (n - 1))) % n;
  }
  return { ...MOTIVATIONAL_QUOTES[i], index: i };
}

export function getQuoteCount() {
  return MOTIVATIONAL_QUOTES.length;
}
